version: '3.8'

services:
  # Base de Dados PostgreSQL
  postgres:
    image: postgres:15
    container_name: bofa_postgres
    environment:
      POSTGRES_USER: claudio
      POSTGRES_PASSWORD: bofa_password
      POSTGRES_DB: transaction_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U claudio -d transaction_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Gerenciador do Kafka (Zookeeper)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: bofa_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: bofa_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5